package mykotlin

//TO CHECK THE OUPUT QUICKLY use REPL
/*STEPS
* MENU
* TOOLS
* KOTLIN
* KOTLIN REPL EXPERIMENT
* DIRECTLY WRITE THE CODE PRESS CTRL+ENTER INSTANTLY GET THE OUTPUT
* */
fun main(){

}